create table if not exists category (
    id bigint generated by default as identity primary key,
    name varchar(50) unique
);

create table if not exists user_account (
    id bigint generated by default as identity primary key,
    email varchar(50) unique,
    name varchar(50)
);

create table if not exists event (
    id bigint generated by default as identity primary key,
    title varchar,
    annotation varchar,
    description varchar,
    paid bool,
    request_moderation bool,
    category_id bigint references category,
    location_lat float,
    location_lon float,
    participant_limit int,
    confirmed_requests int,
    created_on timestamp,
    event_date timestamp,
    published_on timestamp,
    initiator_id bigint references user_account,
    state varchar
);

create table if not exists event_request (
    id bigint generated by default as identity primary key,
    event_id bigint references event,
    requester_id bigint references user_account,
    status varchar,
    created timestamp
);

create table if not exists compilation (
    id bigint generated by default as identity primary key,
    title varchar(50),
    pinned bool
);

create table if not exists event_compilation (
    event_id bigint references event,
    compilation_id bigint references compilation,
    primary key (event_id, compilation_id)
);
