create table if not exists category (
    id bigint generated by default as identity primary key,
    name varchar(50) unique
);

create table if not exists user_account (
    id bigint generated by default as identity primary key,
    email varchar(50) unique,
    name varchar(50)
)