create table if not exists category (
    id bigint generated by default as identity primary key,
    name varchar(50) unique
);

create table if not exists user_account (
    id bigint generated by default as identity primary key,
    email varchar(50) unique,
    name varchar(50)
);

create table if not exists event (
    id bigint generated by default as identity primary key,
    title varchar,
    annotation varchar,
    description varchar,
    paid bool,
    request_moderation bool,
    category_id bigint references category,
    location_lat float,
    location_lon float,
    participant_limit int,
    confirmed_requests int,
    created_on timestamp,
    event_date timestamp,
    published_on timestamp,
    views bigint,
    initiator_id bigint references user_account,
    state varchar
)