version: '3.1'
services:
  stats-server:
    build: ./stats/stats-service
    image: stats-service-image
    container_name: stats-service-container
    depends_on:
      - stats-db
    environment:
      - DB_NAME=explorewithme-stats
      - POSTGRES_USER=explorewithme-stats
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=stats-db
      - DB_PORT=5432
      - SERVER_PORT=9090
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    environment:
      - POSTGRES_DB=explorewithme-stats
      - POSTGRES_USER=explorewithme-stats
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
    volumes:
      - /var/lib/postgresql/data/

  ewm-service:
    build: ./main-service
    image: main-service-image
    container_name: main-service-container
    depends_on:
      - ewm-db
      - stats-server
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
    container_name: main-db-container
    ports:
      - "6543"
