version: '3.1'
services:
  stats-server:
    build: ./stats/stats-service
    image: stats-service-image
    container_name: stats-service-container
    depends_on:
      - stats-db
    environment:
      - DB_NAME=explorewithme-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=stats-db
      - DB_PORT=5432
      - SERVER_PORT=9090
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    environment:
      - POSTGRES_DB=explorewithme-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data/

  ewm-service:
    build: ./main-service
    image: main-service-image
    container_name: main-service-container
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - DB_NAME=explorewithme-main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - SERVER_PORT=8080
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7777
    ports:
      - "8080:8080"
      - "7777:7777"

  ewm-db:
    image: postgres:14-alpine
    container_name: main-db-container
    environment:
      - POSTGRES_DB=explorewithme-main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data/