create table if not exists stat_model (
    id bigint generated by default as identity primary key,
    app varchar(50) not null,
    uri varchar(50) not null,
    ip varchar(50) not null,
    created timestamp not null
);